version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: sms-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: sms-backend
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sms-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
    networks:
      - default
    environment:
      - NODE_ENV=production

volumes:
  pgdata:
